name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21.0.3
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.3'
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew

      - name: Build with Gradle
        run: ./app/gradlew build

      - name: Run tests
        run: ./app/gradlew test

      - name: Check code style
        run: ./app/gradlew checkstyleMain