name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21.0.3
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.3'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew

      - name: Build with Gradle
        run: ./app/gradlew build

      - name: Publish code coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./app/build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true