name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21.0.3
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.3'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app

      - name: Run tests
        run: .java-project-71/app/gradlew test

      - name: Check code style
        run: .java-project-71/app/gradlew checkstyleMain